### PR TITLE
Copyright-automation for ending-date.

### PR DESCRIPTION
**Pull request by netetireallyhuman**
This pull request solves issue #4.

### CODE REVIEW

**Review by netetireallyhuman — COMMENTED** [review]
Is okay, going to merge.

**Review by NetEtiReviewer — COMMENTED** [review]
Everything is allright, maybe merged.

**Review by NetEtiReviewer — COMMENTED** [review]
Everything is ok, merge!

**Comment by netetireallyhuman** [comment]
Closed due to github mismatch

**Pull request closed without merging**
